### ISSUE TITLE
Specifying Clustering Parameters

### ISSUE THREAD

**Issue by prokopyev** [pommedeterresautee/projector#6]
I see that colors represent different clusters. What is the algorithm behind clustering though, it is k-means? Would there be a way to fix the number of clusters or set a maximum number of them? Thank you.

**Comment by pommedeterresautee** [comment]
The clustering is based on DBSCAN (https://en.wikipedia.org/wiki/DBSCAN)
Hyper parameters are different from K means, and you can't set directly the number of clusters.
May I ask you why you are asking?
Is the clustering not good enough?

**Comment by prokopyev** [comment]
Thanks @pommedeterresautee, I was asking to be able to communicate to others the exact way it works. So far no concerns about the clustering.
