### ISSUE TITLE
embeddings of full text - more of a question really not an issue

### ISSUE THREAD

**Issue by jwijffels** [pommedeterresautee/projector#7]
Hi @pommedeterresautee 
I'm evaluating this projector package to visualise the embeddings I get out of some starspace models I've created with the ruimtehol R package which works nicely for words, bi/triggrams and embeddings of document categories.
I also have embeddings for the whole documents (a full text) and I'd like them to visualise these also (e.g. visualise similar documents as document xyz) but as it is long text, it makes it harder to visualise instead of just one word.
Do you by any chance have some pointers to ways of visualising such embeddings?

Do you also have pointers somewhere to the parameters which the annoy model and the tsne model is using to see what their exact meaning is. 
Thanks.

**Comment by pommedeterresautee** [comment]
regarding Annoy and TSNE, which parameters hard to understand? May be I can help.
Regarding viz of long text, depends of what you are looking for, if there are some labels, you can add colors or other layers to the viz, ... if not, you may want to extract the most meaningful passage of the text (and yes the answer of what is the most meaningful parts depends of your use case) to explain the data point.
If you are looking for inspiration: http://textvis.lnu.se/

**Comment by jwijffels** [comment]
I'm looking for the annoy model at number_trees and for the tsne method the arguments max_iter, perplexity and transformations.
Yes, I'm indeed looking for inspiration on Friday. Thanks for the link! If you by any chance have something put in the open regarding viz of relevant text (whatever it may be) on an embeddings space - would be glad to skim through it.

**Comment by pommedeterresautee** [comment]
For looking for part of interest, I m more using LDA approach and focus on one dim. May be with embedding like those of starspace I would check if a paragraph is close to the embedding of the full document for instance, but it s less interesting.
For annoy parameters you need to understand that basically each tree randomly split the space in n parts, and more trees you have more division of the space you get. between 10 and 50 seems good. At some point you are just making annoy slow without adding quality. For tsne, each iteration tries to find the best positions of points where some quality from the initial space are preserved. Several parameters deals with the number of tries before stabilizing, number of iterations is the main. Too high, you are just loosing time but quality won't be degraded.

**Comment by jwijffels** [comment]
Hi @pommedeterresautee , many thanks for your time & input. I'll brew up something customised which replaces your hdbscan method with something like groups of relevant terms.

**Comment by pommedeterresautee** [comment]
Please don't hesitate to commit to this project. I am also using star space for RecSys so I will work on the same issues in 1-2 months.
